# Generated by Django 4.0.3 on 2022-03-10 19:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('theater', '0003_movie_downloads'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie_downloads',
            new_name='Downloads',
        ),
    ]
