# Generated by Django 4.0.3 on 2022-03-10 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('theater', '0004_rename_movie_downloads_downloads'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='downloads',
            field=models.ManyToManyField(related_name='+', through='theater.Downloads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='downloads',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='theater.movie'),
        ),
    ]
