# Generated by Django 4.0.3 on 2022-03-20 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0007_actor_uuid_downloads_uuid_language_uuid_movie_uuid_and_more'),
    ]

    operations = [
    ]
