# Generated by Django 4.0.3 on 2022-03-22 09:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0008_auto_20220320_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='upload',
            field=models.FileField(default=django.utils.timezone.now, upload_to='openTHeater/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
