# Generated by Django 4.0.3 on 2022-03-22 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0009_movie_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='theater.language'),
        ),
    ]
