# Generated by Django 4.0.3 on 2022-03-23 08:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0010_alter_movie_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cover',
            field=models.FileField(default=django.utils.timezone.now, upload_to='openTHeater/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
