# Generated by Django 4.1.2 on 2022-11-03 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0011_movie_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='cover',
            field=models.FileField(upload_to='openTheater/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='movie',
            name='upload',
            field=models.FileField(upload_to='openTheater/%Y/%m/%d'),
        ),
    ]
